### ISSUE TITLE
Using create-react-app @Input problem

### ISSUE THREAD

**Issue by rickerd** [cat-react/form#8]
When using create-react-app you aren't allowed to edit the webpack config and adding the decorator for babel.

I found a solution to be able to use create-rect-app and still use this awesome library.
Just want to share this for other people if they run into this problem.
Maybe worth to add this to the README in the FAQ section.

[https://github.com/facebookincubator/create-react-app/issues/411#issuecomment-238974268](https://github.com/facebookincubator/create-react-app/issues/411#issuecomment-238974268)

**Comment by zwenza** [comment]
Hi @rickerd ,

The decorators are just another syntax for a regular HOC so nobody has to use them, it's just nice
to use if you are able to add the plugin in your webpack config.

You are right, this should be mentioned in the FAQs we will add this asap.

Thanks for sharing the information and using our library :)

**Comment by dsumer** [comment]
Now there is a section for this in our README.md
thanks @zwenza for adding!
